services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: recipe_app
    command: [ "python3", "main.py" ]
#    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
    ports:
      - "8000:8000"
    depends_on:
        - db
    restart: unless-stopped

#  redis:
#    image: redis:7
#    container_name: redis_app
#
#  celery:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: .env
#    container_name: celery_app
#    command: celery -A celery_task.setup_celery worker --loglevel=info
#    depends_on:
#      - redis
  db:
    image: postgres:16
    container_name: db
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

#  minio:
#    image: minio/minio
#    container_name: photo-minio
#    restart: unless-stopped
#    env_file:
#      - ./.env
#    ports:
#      - "9001:9001"
#    volumes:
#      - minio_data:/data
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#    command: server --console-address :9001 /data



volumes:
  postgres_data:
  minio_data: